# Generated by Django 3.2 on 2023-08-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('publish_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('clicks', models.TextField()),
                ('summary', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
